//! Build script for the Iwa reputation Groth16 verifier.
//!
//! Reads our Stage 7 snarkjs `verification_key.json` (path given by the
//! `IWA_VK_JSON` environment variable) and generates `vk.rs` in the Cargo
//! output directory. `lib.rs` `include!`s that file, embedding the verification
//! key as static byte arrays so the contract reads no persistent storage.
//!
//! This is our own, self-contained version of the conversion the Nethermind
//! reference does in its `circom2soroban` build step. We re-encode the snarkjs
//! decimal field elements into the byte layout the Soroban BN254 host functions
//! expect:
//!   * G1 point  -> 64 bytes  : x || y                 (big-endian, 32 each)
//!   * G2 point  -> 128 bytes : x.c1 || x.c0 || y.c1 || y.c0  (c1||c0 order!)
//! snarkjs stores Fq2 as `[c0, c1]`, so we swap to Soroban's `c1, c0` order.
//!
//! If `IWA_VK_JSON` is unset we default to the in-repo copy under
//! `testdata/verification_key.json` so `cargo build`/`cargo test` work out of
//! the box.

use std::{env, fmt::Write as _, fs, path::PathBuf};

use num_bigint::BigUint;
use serde_json::Value;

fn main() {
    println!("cargo:rerun-if-env-changed=IWA_VK_JSON");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));

    let path = match env::var("IWA_VK_JSON") {
        Ok(p) => PathBuf::from(p),
        Err(_) => manifest.join("testdata").join("verification_key.json"),
    };
    println!("cargo:rerun-if-changed={}", path.display());

    let json = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read VK file `{}`: {e}", path.display()));
    let content = vk_rs_from_json(&json);
    fs::write(out_dir.join("vk.rs"), content).expect("failed to write vk.rs");
}

/// Decimal field-element string -> 32-byte big-endian array.
fn fq_be32(dec: &str) -> [u8; 32] {
    let bu = BigUint::parse_bytes(dec.as_bytes(), 10)
        .unwrap_or_else(|| panic!("invalid decimal field element: {dec}"));
    let be = bu.to_bytes_be();
    assert!(be.len() <= 32, "field element exceeds 32 bytes: {dec}");
    let mut out = [0u8; 32];
    out[32 - be.len()..].copy_from_slice(&be);
    out
}

/// snarkjs G1 `[x, y, "1"]` -> 64 bytes (x || y).
fn g1_bytes(pt: &Value) -> [u8; 64] {
    let arr = pt.as_array().expect("G1 point must be a JSON array");
    let x = fq_be32(arr[0].as_str().expect("G1.x must be a string"));
    let y = fq_be32(arr[1].as_str().expect("G1.y must be a string"));
    let mut out = [0u8; 64];
    out[..32].copy_from_slice(&x);
    out[32..].copy_from_slice(&y);
    out
}

/// snarkjs G2 `[[x.c0, x.c1], [y.c0, y.c1], ...]` -> 128 bytes in Soroban's
/// c1||c0 order: x.c1 || x.c0 || y.c1 || y.c0.
fn g2_bytes(pt: &Value) -> [u8; 128] {
    let arr = pt.as_array().expect("G2 point must be a JSON array");
    let x = arr[0].as_array().expect("G2.x must be a JSON array");
    let y = arr[1].as_array().expect("G2.y must be a JSON array");
    let x_c0 = fq_be32(x[0].as_str().expect("G2.x.c0 must be a string"));
    let x_c1 = fq_be32(x[1].as_str().expect("G2.x.c1 must be a string"));
    let y_c0 = fq_be32(y[0].as_str().expect("G2.y.c0 must be a string"));
    let y_c1 = fq_be32(y[1].as_str().expect("G2.y.c1 must be a string"));
    let mut out = [0u8; 128];
    out[..32].copy_from_slice(&x_c1);
    out[32..64].copy_from_slice(&x_c0);
    out[64..96].copy_from_slice(&y_c1);
    out[96..].copy_from_slice(&y_c0);
    out
}

fn fmt_bytes(bytes: &[u8]) -> String {
    let mut s = String::from("[");
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            s.push(',');
        }
        write!(s, "0x{b:02x}").expect("write to String");
    }
    s.push(']');
    s
}

fn vk_rs_from_json(json: &str) -> String {
    let v: Value = serde_json::from_str(json).expect("VK file is not valid JSON");

    let alpha = g1_bytes(&v["vk_alpha_1"]);
    let beta = g2_bytes(&v["vk_beta_2"]);
    let gamma = g2_bytes(&v["vk_gamma_2"]);
    let delta = g2_bytes(&v["vk_delta_2"]);

    let ic_arr = v["IC"].as_array().expect("IC must be a JSON array");
    let ic_len = ic_arr.len();
    let ic_items: Vec<String> = ic_arr.iter().map(|pt| fmt_bytes(&g1_bytes(pt))).collect();

    let mut out = String::new();
    writeln!(out, "// Auto-generated by build.rs from our Stage 7 verification_key.json — do not edit.").unwrap();
    writeln!(out, "const VK_ALPHA_G1: [u8; 64] = {};", fmt_bytes(&alpha)).unwrap();
    writeln!(out, "const VK_BETA_G2: [u8; 128] = {};", fmt_bytes(&beta)).unwrap();
    writeln!(out, "const VK_GAMMA_G2: [u8; 128] = {};", fmt_bytes(&gamma)).unwrap();
    writeln!(out, "const VK_DELTA_G2: [u8; 128] = {};", fmt_bytes(&delta)).unwrap();
    writeln!(out, "const VK_IC: [[u8; 64]; {ic_len}] = [{}];", ic_items.join(",")).unwrap();
    out
}
