#![no_std]

//! Iwa reputation Groth16 verifier (BN254) for Soroban.
//!
//! Verifies the zero-knowledge reputation proofs produced by our Stage 7
//! circuit / Stage 8 on-device prover. A member proves — without revealing their
//! secret or raw numbers — that they are a member of the savings circle and meet
//! a reputation threshold. This contract checks that proof entirely on-chain
//! using Stellar's native BN254 pairing precompile.
//!
//! The verification key embedded here is our own circuit's key (Stage 7
//! `verification_key.json`), converted to Soroban byte order by `build.rs`. The
//! verifier itself is adapted from the structure of the Nethermind
//! `circom-groth16-verifier` reference, but is independent code targeting our
//! circuit.
//!
//! Public seam (matches the PRD): `verify_proof(proof, public_signals) -> bool`.
//!   * `proof`           : 256 bytes = A (G1, 64) || B (G2, 128) || C (G1, 64),
//!                         G2 in Soroban c1||c0 order (as our prover emits).
//!   * `public_signals`  : the circuit's public signals as 32-byte big-endian
//!                         field elements: [nullifier, threshold, root].

extern crate alloc;

use soroban_sdk::{
    contract, contractimpl,
    crypto::bn254::{Bn254Fr, Bn254G1Affine as G1Affine, Bn254G2Affine as G2Affine},
    vec, Bytes, BytesN, Env, Vec,
};

// Compile-time VK constants generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/vk.rs"));

const G1_SIZE: u32 = 64;
const G2_SIZE: u32 = 128;
const PROOF_SIZE: u32 = G1_SIZE + G2_SIZE + G1_SIZE; // 256

struct VerificationKey {
    alpha: G1Affine,
    beta: G2Affine,
    gamma: G2Affine,
    delta: G2Affine,
    ic: Vec<G1Affine>,
}

fn embedded_vk(env: &Env) -> VerificationKey {
    let mut ic: Vec<G1Affine> = Vec::new(env);
    for bytes in VK_IC.iter() {
        ic.push_back(G1Affine::from_bytes(BytesN::from_array(env, bytes)));
    }
    VerificationKey {
        alpha: G1Affine::from_bytes(BytesN::from_array(env, &VK_ALPHA_G1)),
        beta: G2Affine::from_bytes(BytesN::from_array(env, &VK_BETA_G2)),
        gamma: G2Affine::from_bytes(BytesN::from_array(env, &VK_GAMMA_G2)),
        delta: G2Affine::from_bytes(BytesN::from_array(env, &VK_DELTA_G2)),
        ic,
    }
}

/// Parse the 256-byte serialized proof into its three curve points.
fn parse_proof(proof: &Bytes) -> Option<(G1Affine, G2Affine, G1Affine)> {
    if proof.len() != PROOF_SIZE {
        return None;
    }
    let a = G1Affine::from_bytes(proof.slice(0..G1_SIZE).try_into().ok()?);
    let b = G2Affine::from_bytes(proof.slice(G1_SIZE..G1_SIZE + G2_SIZE).try_into().ok()?);
    let c = G1Affine::from_bytes(proof.slice(G1_SIZE + G2_SIZE..).try_into().ok()?);
    Some((a, b, c))
}

#[contract]
pub struct IwaReputationVerifier;

#[contractimpl]
impl IwaReputationVerifier {
    /// Verify a reputation proof against the embedded circuit verification key.
    ///
    /// Returns `true` iff `proof` is a valid Groth16 proof for `public_signals`.
    /// Returns `false` for a tampered/invalid proof, a malformed proof, or a
    /// public-signal count that does not match the circuit (3 signals).
    pub fn verify_proof(env: Env, proof: Bytes, public_signals: Vec<BytesN<32>>) -> bool {
        let (a, b, c) = match parse_proof(&proof) {
            Some(p) => p,
            None => return false,
        };

        let vk = embedded_vk(&env);

        // One IC entry per public signal, plus the constant term.
        if public_signals.len().checked_add(1) != Some(vk.ic.len()) {
            return false;
        }

        let bn = env.crypto().bn254();

        // vk_x = IC[0] + sum_i public_signals[i] * IC[i+1]
        let mut vk_x = match vk.ic.get(0) {
            Some(p) => p,
            None => return false,
        };
        for i in 0..public_signals.len() {
            let signal = match public_signals.get(i) {
                Some(s) => Bn254Fr::from_bytes(s),
                None => return false,
            };
            let ic = match vk.ic.get(i + 1) {
                Some(p) => p,
                None => return false,
            };
            let term = bn.g1_mul(&ic, &signal);
            vk_x = bn.g1_add(&vk_x, &term);
        }

        // Groth16 pairing check:
        // e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1
        #[allow(clippy::arithmetic_side_effects)]
        let neg_a = -a;
        let g1_points = vec![&env, neg_a, vk.alpha, vk_x, c];
        let g2_points = vec![&env, b, vk.beta, vk.gamma, vk.delta];

        bn.pairing_check(g1_points, g2_points)
    }
}

#[cfg(test)]
mod test;
