// Pins the browser signer to the SAME fixed vectors that
// contracts/starknet/tests/test_hash_parity.cairo asserts against the deployed
// contract's own corelib calls. If this file and the chain ever disagree, this
// test fails offline, before a transaction is built.
//
// Vectors regenerated by: node scripts/demo/00_vectors.mjs

import { describe, expect, it } from "vitest";

import {
  authPublicKey,
  contributionSettlementHash,
  cureSettlementHash,
  deriveMemberIdentity,
  memberRef,
  payoutAuthorizationHash,
  payoutSettlementHash,
  recoverySettlementHash,
  shortStringToFelt,
  signChecked,
  signIwa,
  verifyIwa,
} from "./iwaSigning";

// Published fixture key. Never used to hold value.
const SECRET_A = 0x112233445566778899aabbccddeeff00112233445566778899aabbccddeeffn;
const KEY_A_PRIV = 0x1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234n;
const HELPER = 0x04cac02dcc7ca8c46c0b6f32985f17bf24d99557222e60c6881d147e13fafbbbn;
const POOL = 0x040337b1af3c663e86e333bab5a4b28da8d4652a15a69beee2b677776ffe812an;
const USDC = 0x033068f6539f8e6e6b131e6b2b814e6c34a5224bc66947c47dab9dfee93b35fbn;
const AMOUNT = 1_000_000n;
const PAYOUT_AMOUNT = 2_000_000n;
const OPEN_NOTE = 0xdeadbeefcafebaben;

// Expected values pinned in test_hash_parity.cairo.
const KEY_A = 0x60b6e4b10b64fa926d072859c75c390cdb47df415e2a2bd960bd19e3601642fn;
const MEMBER_REF = 0x301473563c9095055be74afaa57bdc8fc13165de2997a759154f30305f23424n;
const CONTRIB = 0x65c8c87a4fd7fbcaf1f0461aa7b36989b3389161f21f34ddb4e6fb4ab2a0377n;
const CURE = 0x3dc1472d129d829ce3a9b2f9b667f5cd4e8e581fcf17a8b30c561324fd0f71n;
const PAYOUT_AUTH = 0x2e42b5b5bd506b84201c611bdd56403ba682067d28fb6d48d584467a6927543n;
const PAYOUT_SETTLE = 0x2cc3662fe43fc81c1701341b62757ee05fc5cacf92075cd4088bb5626cdd1ecn;
const RECOVERY_SETTLE = 0x3957bda4c74ed3dd10a433b52dca07c384b6f85a0199ba43786d8f3256e11f4n;
const SIG_R = 0x5bbe7ef01d10af3c63dbe12a271c8f2c2ee82659fa6fc1cf185a05159cd0e8fn;
const SIG_S = 0x1c0c5f5fea005a22ac61b8e24b3eb5a49b932dd02367ce73855bdb7f25901c2n;

const CURVE_ORDER = 0x800000000000010ffffffffffffffffb781126dcae7b2321e66a241adc64d2fn;

const base = {
  circleId: 1n,
  round: 1n,
  memberRef: MEMBER_REF,
  helper: HELPER,
  pool: POOL,
  token: USDC,
};

describe("short strings", () => {
  it("encodes a Cairo domain tag", () => {
    expect(shortStringToFelt("IWA_INVITE_V1")).toBe(0x4957415f494e564954455f5631n);
  });
});

describe("hash parity with the deployed contract", () => {
  it("derives the pinned auth public key", () => {
    expect(authPublicKey(KEY_A_PRIV)).toBe(KEY_A);
  });

  it("derives the pinned member_ref", () => {
    expect(memberRef(SECRET_A, KEY_A)).toBe(MEMBER_REF);
  });

  it("matches the contribution settlement hash", () => {
    expect(contributionSettlementHash({ ...base, amount: AMOUNT, nonce: 1n })).toBe(CONTRIB);
  });

  it("matches the cure settlement hash", () => {
    expect(cureSettlementHash({ ...base, amount: AMOUNT, nonce: 2n })).toBe(CURE);
  });

  it("matches the payout authorization hash", () => {
    expect(
      payoutAuthorizationHash({
        circleId: 1n,
        round: 1n,
        memberRef: MEMBER_REF,
        amount: PAYOUT_AMOUNT,
        nonce: 3n,
      }),
    ).toBe(PAYOUT_AUTH);
  });

  it("matches the payout settlement hash", () => {
    expect(
      payoutSettlementHash({
        ...base,
        amount: PAYOUT_AMOUNT,
        openNoteId: OPEN_NOTE,
        nonce: 4n,
      }),
    ).toBe(PAYOUT_SETTLE);
  });

  it("matches the recovery settlement hash", () => {
    expect(
      recoverySettlementHash({
        ...base,
        amount: PAYOUT_AMOUNT,
        openNoteId: OPEN_NOTE,
        nonce: 5n,
      }),
    ).toBe(RECOVERY_SETTLE);
  });

});

describe("signature parity", () => {
  it("reproduces the exact signature pinned in the Cairo test", () => {
    const sig = signIwa(KEY_A_PRIV, CONTRIB);
    expect(sig.r).toBe(SIG_R);
    expect(sig.s).toBe(SIG_S);
  });

  it("accepts it under the contract predicate", () => {
    expect(verifyIwa(KEY_A, CONTRIB, SIG_R, SIG_S)).toBe(true);
  });

  it("rejects the high-s malleable twin", () => {
    expect(verifyIwa(KEY_A, CONTRIB, SIG_R, CURVE_ORDER - SIG_S)).toBe(false);
  });

  it("rejects a signature over a different message", () => {
    expect(verifyIwa(KEY_A, CONTRIB + 1n, SIG_R, SIG_S)).toBe(false);
  });

  it("rejects a zero auth key", () => {
    expect(verifyIwa(0n, CONTRIB, SIG_R, SIG_S)).toBe(false);
  });
});

describe("member identity", () => {
  it("derives the pinned commitment without exposing the key", () => {
    const id = deriveMemberIdentity("A", SECRET_A, KEY_A_PRIV);
    expect(id.authPublicKeyX).toBe(KEY_A);
    expect(id.memberRef).toBe(MEMBER_REF);
  });

  it("signChecked returns only signatures the chain would accept", () => {
    const id = deriveMemberIdentity("A", SECRET_A, KEY_A_PRIV);
    const sig = signChecked(id, CONTRIB, "contribution settlement");
    expect(sig.r).toBe(SIG_R);
    expect(sig.s).toBe(SIG_S);
  });
});
