// Hash and signature parity lock between the JavaScript demo tooling and the
// deployed Cairo contracts.
//
// The demo (scripts/demo/) computes member refs, settlement message hashes,
// and Stark-curve signatures with starknet.js 10.5.0
// (`ec.starkCurve.poseidonHashMany` + `ec.starkCurve.sign`, low-s normalized).
// This test pins FIXED vectors computed by that tooling and asserts them
// against the exact corelib functions the deployed IwaCircle uses, so any
// divergence between the JS poseidon construction and Cairo's
// `poseidon_hash_span` (or between the JS signer and `check_ecdsa_signature`)
// fails here, offline, before a single mainnet transaction.
//
// Signature convention (Cairo v2.18 corelib): `check_ecdsa_signature`
// reconstructs both the public key point and the R point from their
// x-coordinates and accepts when `(zG + rQ).x == sR.x` OR
// `(zG - rQ).x == sR.x`. It compares x-coordinates only and tries both signs
// of rQ, so the y-root the VM picks for the reconstructed key is irrelevant:
// `signIwa` in lib/iwa.mjs signs with the true private key and applies no key
// normalization, only the canonical low-s the contract's
// `verify_settlement_hash` requires.
//
// Vectors regenerated by: node scripts/demo/00_vectors.mjs

use iwa::iwa_types::{
    contribution_settlement_authorization_hash, cure_settlement_authorization_hash,
    invite_commitment, is_valid_auth_public_key, payout_authorization_hash,
    payout_settlement_authorization_hash, recovery_settlement_authorization_hash,
    verify_contribution_settlement_authorization,
};
use starknet::ContractAddress;

// --- Fixed inputs (shared with scripts/demo/00_vectors.mjs) ---
const SECRET_A: felt252 = 0x112233445566778899aabbccddeeff00112233445566778899aabbccddeeff;
const KEY_A: felt252 = 0x60b6e4b10b64fa926d072859c75c390cdb47df415e2a2bd960bd19e3601642f;
const CIRCLE_ID: u32 = 1;
const ROUND: u32 = 1;
const HELPER: felt252 = 0x04cac02dcc7ca8c46c0b6f32985f17bf24d99557222e60c6881d147e13fafbbb;
const POOL: felt252 = 0x040337b1af3c663e86e333bab5a4b28da8d4652a15a69beee2b677776ffe812a;
const USDC: felt252 = 0x033068f6539f8e6e6b131e6b2b814e6c34a5224bc66947c47dab9dfee93b35fb;
const AMOUNT: u128 = 1_000_000;
const PAYOUT_AMOUNT: u128 = 2_000_000;
const OPEN_NOTE: felt252 = 0xdeadbeefcafebabe;

// --- Expected values from the JS tooling ---
const EXPECTED_MEMBER_REF: felt252 =
    0x301473563c9095055be74afaa57bdc8fc13165de2997a759154f30305f23424;
const EXPECTED_CONTRIB: felt252 = 0x65c8c87a4fd7fbcaf1f0461aa7b36989b3389161f21f34ddb4e6fb4ab2a0377;
const EXPECTED_CURE: felt252 = 0x3dc1472d129d829ce3a9b2f9b667f5cd4e8e581fcf17a8b30c561324fd0f71;
const EXPECTED_PAYOUT_AUTH: felt252 =
    0x2e42b5b5bd506b84201c611bdd56403ba682067d28fb6d48d584467a6927543;
const EXPECTED_PAYOUT_SETTLE: felt252 =
    0x2cc3662fe43fc81c1701341b62757ee05fc5cacf92075cd4088bb5626cdd1ec;
const EXPECTED_RECOVERY_SETTLE: felt252 =
    0x3957bda4c74ed3dd10a433b52dca07c384b6f85a0199ba43786d8f3256e11f4;
const SIG_R: felt252 = 0x5bbe7ef01d10af3c63dbe12a271c8f2c2ee82659fa6fc1cf185a05159cd0e8f;
const SIG_S: felt252 = 0x1c0c5f5fea005a22ac61b8e24b3eb5a49b932dd02367ce73855bdb7f25901c2;

fn helper() -> ContractAddress {
    HELPER.try_into().unwrap()
}
fn pool() -> ContractAddress {
    POOL.try_into().unwrap()
}
fn usdc() -> ContractAddress {
    USDC.try_into().unwrap()
}

#[test]
fn test_member_ref_parity() {
    assert(invite_commitment(SECRET_A, KEY_A) == EXPECTED_MEMBER_REF, 'member ref mismatch');
    assert(is_valid_auth_public_key(KEY_A), 'invalid auth curve point');
}

#[test]
fn test_contribution_hash_parity() {
    let member = invite_commitment(SECRET_A, KEY_A);
    assert(
        contribution_settlement_authorization_hash(
            CIRCLE_ID, ROUND, member, helper(), pool(), usdc(), AMOUNT, 1,
        ) == EXPECTED_CONTRIB,
        'contribution hash mismatch',
    );
}

#[test]
fn test_cure_hash_parity() {
    let member = invite_commitment(SECRET_A, KEY_A);
    assert(
        cure_settlement_authorization_hash(
            CIRCLE_ID, ROUND, member, helper(), pool(), usdc(), AMOUNT, 2,
        ) == EXPECTED_CURE,
        'cure hash mismatch',
    );
}

#[test]
fn test_payout_auth_hash_parity() {
    let member = invite_commitment(SECRET_A, KEY_A);
    assert(
        payout_authorization_hash(
            CIRCLE_ID, ROUND, member, PAYOUT_AMOUNT, 3,
        ) == EXPECTED_PAYOUT_AUTH,
        'payout auth hash mismatch',
    );
}

#[test]
fn test_payout_settlement_hash_parity() {
    let member = invite_commitment(SECRET_A, KEY_A);
    assert(
        payout_settlement_authorization_hash(
            CIRCLE_ID, ROUND, member, helper(), pool(), usdc(), PAYOUT_AMOUNT, OPEN_NOTE, 4,
        ) == EXPECTED_PAYOUT_SETTLE,
        'payout settlement hash mismatch',
    );
}

#[test]
fn test_recovery_settlement_hash_parity() {
    let member = invite_commitment(SECRET_A, KEY_A);
    assert(
        recovery_settlement_authorization_hash(
            CIRCLE_ID, ROUND, member, helper(), pool(), usdc(), PAYOUT_AMOUNT, OPEN_NOTE, 5,
        ) == EXPECTED_RECOVERY_SETTLE,
        'recovery settle hash mismatch',
    );
}

#[test]
fn test_js_signature_verifies_onchain_style() {
    // The JS signer produced (SIG_R, SIG_S) over the contribution message with
    // the member's auth private key. The deployed verifier (x-coordinate
    // reconstruction, canonical low-s) must accept it.
    let member = invite_commitment(SECRET_A, KEY_A);
    assert(
        verify_contribution_settlement_authorization(
            KEY_A, CIRCLE_ID, ROUND, member, helper(), pool(), usdc(), AMOUNT, 1, SIG_R, SIG_S,
        ),
        'js signature must verify',
    );
}
